kind: pipeline
name: qa_devops

steps:
- name: check_guidelines
  image: python:2.7
  commands:
  - python qa/check_readme.py
  when:
    branch:
    - dev
    - test
    - master

- name: solo master
  image: python:2.7
  commands:
  - echo solo master
  when:
    branch:
    - master