kind: pipeline
name: qa_devops

steps:
- name: check_readme
  image: jjvargass/qa_develoment:0.1
  commands:
  - python /app/check_readme.py
  when:
    branch:
    - dev
    - test
    - master

- name: check_branch
  image: jjvargass/qa_develoment:0.1
  commands:
  - python /app/check_branch.py
  when:
    branch:
    - dev
    - test
    - master

- name: check_commits
  image: jjvargass/qa_develoment:0.1
  commands:
  - python /app/check_commits.py
  when:
    branch:
    - dev
    - test
    - master

- name: slack_notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_AND_WEBHOOK
    channel: ci-develop
    link_names: true
    template: >
      {{#if build.pull }}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
      {{else}}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
      {{/if}}
      *Repo:* {{ repo.name }}
      *Branch:* <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
      *Commit:* <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

      Author: {{ build.author }}

      <{{ build.link }}|Visit build page ↗>
  when:
    branch:
    - dev
    - test
    - master
    status:
    - failure
    - success

---

kind: pipeline
name: deploy_client

steps:
- name: deploy
  image: alpine
  commands:
  - echo hello world
  when:
    branch:
    - dev
    - test
    - master