kind: pipeline
name: qa_devops

steps:
- name: check_guidelines
  image: python:2.7
  commands:
  - echo hello
  - echo hello 2 error
  - echo world
  when:
    branch:
    - dev
    - test

- name: solo master
  image: python:2.7
  commands:
  - echo solo master
  when:
    branch:
    - master