kind: pipeline
name: qa_devops

steps:
- name: check_readme
  image: python:2.7
  commands:
  - python qa/check_readme.py
  when:
    branch:
    - dev
    - test
    - master

- name: check_branch
  image: python:2.7
  commands:
  - pip install gitpython
  - python qa/check_branch.py
  when:
    branch:
    - dev
    - test
    - master