kind: pipeline
name: qa_devops

steps:
- name: check_readme
  image: python:2.7
  commands:
  - python qa/check_readme.py
  when:
    branch:
    - dev
    - test
    - master

- name: check_branch
  image: python:2.7
  commands:
  - pip install gitpython
  - python qa/check_branch.py
  when:
    branch:
    - dev
    - test
    - master

- name: slack_notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: webhook_and
    channel: ci-develop
    link_names: true
      template: >
        {{#success build.status}}
          [{{repo.name}}] [{{build.branch}}] [{{build.number}}] Succeeded by {{build.author}}
        {{else}}
          [{{repo.name}}] [{{build.branch}}] [{{build.number}}] Failed by {{build.author}}
          Please visit {{build.link}} for more details.
        {{/success}}
    when:
      status: [ success, failure ]

---

kind: pipeline
name: deploy_client

steps:
- name: deploy
  image: alpine
  commands:
  - echo hello world
  when:
    branch:
    - dev
    - test
    - master