version: '2'
services:
  odoo-db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
  odoo_v9:
    image: jjvargass/odoo:9.0
    ports:
      - "8069:8069"
    depends_on:
      - odoo-db
    volumes:
     - ./extra-addons:/opt/addons/
     - ./odoo_v9/logs/odoo:/var/log/odoo/
     - ./odoo_v9/logs/supervisor:/var/log/supervisor
     - ./odoo_v9/attachments/data:/opt/odoo-attachments/data/