version: '2'
services:
  odoo:
    image: odoo:9
    restart: always
    ports:
      - "8069:8069"
    links:
      - db
    volumes:
    #  - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
